version: '3'

services:
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: mysql:5
    volumes:
        - mysql-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - .docker/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_HOST=${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - mysql

volumes:
  mysql-data:
