version: '3'

services:
  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    build: 
      context: ./.docker/mysql
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
        - ./data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    volumes:
      - .docker/phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_ABSOLUTE_URI=${PMA_ABSOLUTE_URI}
      - PMA_HOST=${COMPOSE_PROJECT_NAME}_mysql
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - mysql
